### ISSUE TITLE
Doleance 

### ISSUE THREAD

**Issue by excellencemichel** [Mohit090301/Connect-Public#1]
Hi ! Please,can you let me fork the code

**Comment by Mohit090301** [comment]
Hello Michel,
I am afraid I won't be able to share my code as I have made the code
private since I have added a lot more features to this app which I am not
willing to share with anyone.
Can I know why exactly do you want the code?

Mohit

**Comment by excellencemichel** [comment]
I am working on a personal project in which I want to integrate internal messaging functionality; what I managed to do is not very convenient (my level in Dart and Flutter is not very advanced).
Reason why I want you to help me,

**Comment by Mohit090301** [comment]
I understand but I have added certain functionalities and features which aren't there in any app yet and as a result I can't share my code to anyone.
